# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dphoto', models.ImageField(upload_to='prophotos/')),
                ('bio', models.CharField(max_length=250)),
            ],
        ),
    ]
