# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_auto_20190311_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.CharField(max_length=1000),
        ),
    ]
