# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0008_auto_20190312_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='username',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
