# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0010_auto_20190312_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='dpicture',
            field=models.ImageField(upload_to='prophotos/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
