# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 12:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gram', '0011_auto_20190312_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=20)),
                ('image_caption', models.CharField(max_length=1000)),
                ('likes', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=250)),
                ('image_path', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gram.Profile')),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
    ]
