# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0013_remove_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='username',
        ),
    ]
